name: To deploy static website in S3 bucket For QA

on:
  pull_request:
    branches: 
       - develop

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 2.6
    - name: "Build Site"
      run: bundle exec jekyll build
       
