name: To deploy static website in S3 bucket For QA

on:
  pull_request:
    branches: 
       - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_QA }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_QA }}
        aws-region:  ${{ secrets.AWS_REGION_QA }}
        
    - name: Deploy static site to S3 bucket in help folder
      run: aws s3 sync ./_site/ s3://www.7targets-qa.ai/help/    
   
    - name: Deploy static site to S3 bucket in blog folder
      run: aws s3 sync ./_site/ s3://www.7targets-qa.ai/blog/
