name: To deploy static website in S3 bucket For QA

on:
  pull_request:
    branches: 
       - develop

jobs:

 build:
  
   runs-on: ubuntu-latest
   steps:
      
     - uses: actions/checkout@v2

     - name: Build
       uses: ealenn/jekyll-build-action@v1
      
     - name: update bundler  
       run: bundle update --bundler

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_QA }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_QA }}
         aws-region: ${{ secrets.AWS_REGION_QA }}

     - name: Sync output to S3
       run: |
          aws s3 sync ./_site/ s3://www.7targets-qa.ai/help --delete
