name: To deploy static website in S3 bucket For QA

on:
  pull_request:
    branches: 
       - develop

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    # Standard usage
    - uses:  lemonarc/jekyll-action@1.0.0
    
    # Example deployment: Push to S3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_QA }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_QA }}
       aws-region:  ${{ secrets.AWS_REGION_QA }}
       
    - name: Deploy static site to S3 bucket in help folder
      run: aws s3 sync ./_site/ s3://www.7targets-qa.ai/help/  --delete  
   
    - name: Deploy static site to S3 bucket in blog folder
      run: aws s3 sync ./_site/ s3://www.7targets-qa.ai/blog/  --delete

       
